export const CHANGE_CURRENT_TIME = 'CHANGE_CURRENT_TIME';
export const CHANGE_PATH = 'CHANGE_PATH';
export const CHANGE_PLAYING_SONG = 'CHANGE_PLAYING_SONG';
export const CHANGE_SELECTED_PLAYLISTS = 'CHANGE_SELECTED_PLAYLISTS';
export const RECEIVE_SONGS = 'RECEIVE_SONGS';
export const REQUEST_SONGS = 'REQUEST_SONGS';
export const CHANGE_PLAYER_STATUS = 'CHANGE_PLAYER_STATUS'
