export const RECEIVE_EVENTS = 'RECEIVE_EVENTS';
export const REQUEST_EVENTS = 'REQUEST_EVENTS';
export const SEARCH_EVENTS =  'SEARCH_EVENTS';
export const DATE_SELECTED = 'DATE_SELECTED';
export const REQUEST_EVENT_DETAILS = 'REQUEST_EVENT_DETAILS';
export const COLLAPSE_HEADER = 'COLLAPS_HEADER';